name: flutter_shop
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^2.0.7
  # 轮播图插件 https://github.com/jzoom/flutter_swiper
  flutter_swiper: ^1.1.6
  flutter_screenutil: ^0.5.1
  shared_preferences: ^0.4.3
  # 拨打电话，发信息，打开第三方等等 https://github.com/flutter/plugins/blob/master/packages/url_launcher
  url_launcher: ^5.0.1
  flutter_easyrefresh: ^1.2.7
  provide: ^1.0.2
  # toast弹窗提示 https://github.com/PonnamKarthik/FlutterToast
  fluttertoast: ^3.0.1
  scoped_model: ^1.0.1
  # 程序包信息获取 https://github.com/flutter/plugins/blob/master/packages/package_info
  package_info: ^0.4.0+3
  # 获取设备信息 https://github.com/flutter/plugins/blob/master/packages/device_info
  device_info: ^0.4.0+1   
  # 本地数据库 https://github.com/tekartik/sqflite
  sqflite: ^0.12.1 
  # 城市列表选择 https://github.com/flutterchina/azlistview
  azlistview: ^0.1.1
  # 城市列表选择配套插件用于汉字拼音转换 https://github.com/flutterchina/lpinyin
  lpinyin: ^1.0.7
  # 时间选择插件 https://github.com/Realank/flutter_datetime_picker
  flutter_datetime_picker: ^1.1.4
  # 二维码条码扫描 https://github.com/apptreesoftware/flutter_barcode_reader
  barcode_scan: ^1.0.0
  # 国家代码 https://github.com/Salvatore-Giordano/CountryCodePicker
  country_code_picker: ^1.1.5
  # 麻省-多图片选择器 https://github.com/Sh1d0w/multi_image_picker
  multi_image_picker: ^4.1.2
  # 官方-图片选择器 https://github.com/flutter/plugins/tree/master/packages/image_picker
  # image_picker: ^0.5.2
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.1.1
  # 富文本编辑器 https://github.com/memspace/zefyr
  zefyr: ^0.5.0
 
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - locale/
    - assets/
    - assets/data/
    - assets/images/

  fonts:
    - family: IconFont
      fonts:
        - asset: assets/fonts/iconfont.ttf
          weight: 400
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
